# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: oargrave <oargrave@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/10/29 19:52:50 by oargrave          #+#    #+#              #
#    Updated: 2019/10/30 06:41:35 by oargrave         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

CC=clang
FILE = src/ft_vector.c test_files/main.c src/meta.c src/push.c

all: 
	$(CC) -g $(FILE) -I ../memory_registration/includes ../memory_registration/ft_malloc.a	